/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;
import HogwartLibrary.Book;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;

public class BookRepository extends RepoBase<Book> implements IBookRepository{

	public BookRepository(Connection connection,

						  IMapResultSetIntoEntity mapper, IUnitOfWork uow) {

		super(connection, mapper, uow);

	}

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "Book";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE Book("

				+ "idBook bigint GENERATED BY DEFAULT AS IDENTITY,"
                        
                                + "ISBN VARCHAR(20),"

				+ "title VARCHAR(100)," 

				+ "section VARCHAR(100),"
                        
				+ "availability boolean,"
                        
                                + "idAuthor bigint"

				+ ")   "
                        
                                + "ALTER TABLE Book" +
                                "ADD FOREIGN KEY (idAuthor) " +
                                "REFERENCES Author(id)";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO Book (idBook, isbn, title, section, availability, idAuthor) VALUES (?, ?, ? , ?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM Book WHERE idBook = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE Book SET isbn = ?, title = ?, section = ?, availability = ?  WHERE isbn = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM Book WHERE idBook =?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM Book";

	}

	

	@Override
        protected void setupInsert(Book entity) throws SQLException {

                insert.setInt(1, entity.getIdBook());
                
		insert.setString(2, entity.getISBN());

		insert.setString(3, entity.getTitle());

		insert.setString(4, entity.getSection());
                
                insert.setBoolean(5, entity.getAvailability());
                
                insert.setInt(6, entity.getAuthor().getId());
                

		

	}



	@Override
	protected void setupUpdate(Book entity) throws SQLException {

		update.setString(1, entity.getISBN());

		update.setString(2, entity.getTitle());

		update.setString(3, entity.getSection());
                
		update.setBoolean(4, entity.getAvailability());
                
                update.setInt(5, entity.getIdBook());



	}

	public List<Book> withAuthor(String author) {

		// TODO Auto-generated method stub

		return null;

	}

	public List<Book> withHistory(String history) {

		// TODO Auto-generated method stub

		return null;

	}


}