package dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class EnumDictionary {

private Connection connection;
	
	private String createTableSql = "CREATE TABLE EnumDictionary("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "INT key,"
			+ "key VARCHAR(50)"
			+ "INT value,"
			+ "EnumerationName VARCHAR(50)"
			+ ")";
	private Statement createTable;
	
	public EnumDictionary(Connection connection) {
		this.connection = connection;
		
		try {
			createTable = connection.createStatement();
			
			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			while(rs.next()){
				if(rs.getString("TABLE_NAME").equalsIgnoreCase("EnumDictionary")){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
				
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
}
