package dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class EnumDictionaryRepository {

private Connection connection;
	
	private String createTableSql = "CREATE TABLE enumDictionary("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "intKey INT,"
			+ "stringKey VARCHAR(50),"
			+ "value VARCHAR(50),"
			+ "enumName VARCHAR(50),"
			+ ")";
	private Statement createTable;
	
	public EnumDictionaryRepository(Connection connection) {
		this.connection = connection;
		
		try {
			createTable = connection.createStatement();
			
			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			while(rs.next()){
				if(rs.getString("TABLE_NAME").equalsIgnoreCase("enumDictionary")){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
				
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	
	
	
}
