package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import domain.model.HistoryLog;
import domain.model.Person;

public class HistoryLogRepository {
	
	private Connection connection;
	
	private String createTableSql = "CREATE TABLE historyLog("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "date DATE,"
			+ "amount DECIMAL(7,2),"
			+ "accountfrom BIGINT,"
			+ "accountto BIGINT,"
			+ "rate DECIMAL(7,2),"
			+ "operation BIGINT"
			+ ")";
	
	private Statement createTable;

	private String insertSql = "INSERT INTO historyLog(date,amount,accountfrom,accountto,rate,operation) VALUES(?,?,?,?,?,?)";
	private String deleteSql = "DELETE FROM historyLog WHERE id = ?";
	private String updateSql = "UPDATE historyLog set date=?, amount=?, accountfrom=?, accountto=?, rate=?, operation=? WHERE id=?";
	private String selectByIdSql = "SELECT * FROM historyLog WHERE id=?";
	private String selectAllSql = "SELECT * FROM historyLog";
	
	private PreparedStatement insert;
	private PreparedStatement delete;
	private PreparedStatement update;
	private PreparedStatement selectById;
	private PreparedStatement selectAll;
	
	public HistoryLogRepository(Connection connection) {
		this.connection = connection;
		
		try {
			createTable = connection.createStatement();
			
			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null, null, null, null, null);
			while(rs.next()){
				if(rs.getString("TABLE_NAME").equalsIgnoreCase("historylog")){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
				
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public HistoryLog get(int historyLogId){
		try{
			
			selectById.setInt(1, historyLogId);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				HistoryLog result = new HistoryLog();
				result.setId(historyLogId);
				result.setAccount();
				result.setDate();
				result.setAmount(rs.getDouble("amount"));
				result.setFrom();
				result.setTo();
				result.setRate();
				result.setType();
				return result;
			}
		}
		catch(SQLException ex){
			ex.printStackTrace();
		}
		return null;
	}
	
	public void delete(HistoryLog p){
		try{
			delete.setInt(1, p.getId());
			delete.executeUpdate();
		}catch(SQLException ex){
			ex.printStackTrace();
		}
	}
	
	public void add(HistoryLog p){
		try{
			
			insert.setString(1, p.getDate().toString());
			insert.setDouble(2, p.getAmount());
			insert.setInt(3, p.getFrom().getId());
			insert.setInt(4, p.getTo().getId());
			insert.setDouble(5, p.getRate());
			insert.setInt(6, p.getType().ordinal());
			insert.executeUpdate();
			
		}catch(SQLException ex){
			ex.printStackTrace();
		}
		
	}
	
	public void update(HistoryLog p){
		try{
			
			update.setString(1, p.getDate().toString());
			update.setDouble(2, p.getAmount());
			update.setInt(3, p.getFrom().getId());
			update.setInt(4, p.getTo().getId());
			update.setDouble(5, p.getRate());
			update.setInt(6, p.getType().ordinal());
			update.executeUpdate();
			
		}catch(SQLException ex){
			ex.printStackTrace();
		}
		
	}
	
}
