package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.HistoryLog;

public class HistoryLogRepository extends RepositoryBase<HistoryLog> {
	
	public HistoryLogRepository(Connection connection, IMapResultSetIntoEntity<HistoryLog> mapper) {
		super(connection, mapper);
	}
	
	
	@Override
	protected String tableName() {
		return "historyLog";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE historyLog("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "date DATE,"
				+ "amount DECIMAL(7,2),"
				+ "accountfrom BIGINT,"
				+ "accountto BIGINT,"
				+ "rate DECIMAL(7,2),"
				+ "operation BIGINT"
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO historyLog(date,amount,accountfrom,accountto,rate,operation) VALUES(?,?,?,?,?,?)";
	}

	@Override
	protected String deleteSql() {
		return "DELETE FROM historyLog WHERE id = ?";
	}

	@Override
	protected String updateSql() {
		return "UPDATE historyLog set date=?, amount=?, accountfrom=?, accountto=?, rate=?, operation=? WHERE id=?";
	}

	@Override
	protected String selectByIdSql() {
		return "SELECT * FROM historyLog WHERE id=?";
	}

	@Override
	protected String selectAllSql() {
		return "SELECT * FROM historyLog";
	}

	@Override
	protected void setupInsert(HistoryLog entity) throws SQLException {
		insert.setString(1, entity.getDate().toString());
		insert.setDouble(2, entity.getAmount());
		insert.setInt(3, entity.getFrom().getId());
		insert.setInt(4, entity.getTo().getId());
		insert.setDouble(5, entity.getRate());
		insert.setInt(6, entity.getType().ordinal());
		
	}

	@Override
	protected void setupUpdate(HistoryLog entity) throws SQLException {
		update.setString(1, entity.getDate().toString());
		update.setDouble(2, entity.getAmount());
		update.setInt(3, entity.getFrom().getId());
		update.setInt(4, entity.getTo().getId());
		update.setDouble(5, entity.getRate());
		update.setInt(6, entity.getType().ordinal());
		
	}
	
}
