/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;


import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import HogwartLibrary.User;
import dao.uow.IUnitOfWork;
import java.util.List;

public class UserRepository extends RepoBase<User> implements IUserRepository{
    
public UserRepository(Connection connection, 

			IMapResultSetIntoEntity mapper, IUnitOfWork uow) {

		super(connection, mapper, uow);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "User";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE User("

				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "login VARCHAR(20)," 

				+ "password VARCHAR(20),"
                        
                                + "name VARCHAR(20),"
                        
                                + "surname VARCHAR(20),"
                        
                                + "status VARCHAR(20),"
                        
                                + "house VARCHAR(20)"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO User (id ,login, password, name, surname, status, house) VALUES (?, ?, ?, ?, ?, ?, ?)";
 
	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM User WHERE ID = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE User SET id = ?, name = ?, surname = ? WHERE id = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM User WHERE id=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM User";

	}

	

	@Override
        protected void setupInsert(User entity) throws SQLException {

		insert.setInt(1, entity.getId());

		insert.setString(2, entity.getLogin());

		insert.setString(3, entity.getPassword());
                
                insert.setString(4, entity.getName());
                
                insert.setString(5, entity.getSurname());
                
                insert.setString(6, entity.getStatus());
                
                insert.setString(7, entity.getHouse());

		

	}



	@Override
	protected void setupUpdate(User entity) throws SQLException {

		update.setInt(1, entity.getId());

		update.setString(2, entity.getLogin());

		update.setString(3, entity.getPassword());
                
                update.setString(4, entity.getName());
                
                update.setString(5, entity.getSurname());
                
                update.setString(6, entity.getStatus());
                
                update.setString(7, entity.getHouse());



	}


	public List<User> withHistory(String user) {

		// TODO Auto-generated method stub

		return null;

	}

}